package org.antinori.cards.network;

public enum Event {
	
	REMOTE_PLAYER_INFO_INIT,
	REMOTE_PLAYER_CARDS_INIT,
	CARD_HEALTH_AFFECTED,
	PLAYER_HEALTH_AFFECTED,
	PLAYER_STRENGTH_AFFECTED,
	CARD_ADDED,
	CARD_REMOVED,
	ATTACK_AFFECTED,
	SPELL_CAST;

}
